# Generated by Django 5.2.7 on 2025-10-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashify_app', '0003_alter_device_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
